workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Build debug APK
        script: |
          cd HyperBoostFF
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - HyperBoostFF/app/build/outputs/**/*.apk
